// Bilingual content store — Martin Molet, real CV.
const CONTENT = {
  en: {
    nav: ['Index', 'Practices', 'Case studies', 'Experience', 'Contact'],
    meta: {
      role: 'Product Designer · Design System & Design Ops',
      location: 'Marseille / Remote',
      status: 'Open to CDI · Freelance available',
      lastUpdated: 'Apr 2026',
      filename: 'martin-molet.portfolio.v4',
    },
    home: {
      kicker: '01 — Index',
      title: 'I build the systems\nthat let design teams\nship faster.',
      sub: '8+ years as a Product Designer, focused on design systems and design ops. From e-commerce to retail banking, I leave teams with a way of working — not just components.',
      cta1: 'See case studies',
      cta2: 'Get in touch',
      metrics: [
        { value: 40, suffix: '+', label: 'Designers trained on the Société Générale system', note: 'Workshops, open hours, tutorials and written guides — adoption, not push.' },
        { value: 2, suffix: ' → 1', label: 'Design systems unified into a single library', note: 'Client + advisor systems merged, with dedicated modes. Less duplication, fewer drifts.' },
        { value: 8, suffix: '+', label: 'Years shipping production design systems', note: '7 e-commerce sites, retail banking, mobile gaming, telecom subscriptions.' },
      ],
    },
    work: {
      kicker: '02 — Practices',
      title: 'Four practices,\none operating model.',
      sub: 'I treat design as infrastructure. Each practice below is a layer of that stack.',
      sections: [
        {
          id: 'ds',
          tag: 'A',
          title: 'Design System',
          oneLiner: 'A library is not a system. The system is the contract.',
          method: [
            'Audit the existing libraries — components, tokens, drift, debt',
            'Define the contract : naming, structure, governance',
            'Tokenize from the bottom up — primitives → semantic → component',
            'Migrate in waves, never in big bangs',
            'Measure adoption, not output',
          ],
          proof: [
            { k: 'Figma rebuild', v: 'Société Générale libraries restructured for readability, maintainability and adoption.' },
            { k: 'Variables & tokens', v: 'Desktop / mobile variants automated. Manual errors collapsed to near-zero.' },
            { k: '2 → 1 systems', v: 'Client and advisor systems unified into one library with dedicated modes.' },
          ],
        },
        {
          id: 'ops',
          tag: 'B',
          title: 'Design Ops',
          oneLiner: 'Make the right thing the easy thing.',
          method: [
            'Map the design lifecycle end-to-end',
            'Find the friction — handoffs, reviews, naming, files',
            'Standardize what should be standard, free what shouldn\'t',
            'Document usage, rules and constraints — for designers and devs',
            'Run open hours so the system stays a living conversation',
          ],
          proof: [
            { k: 'Operational docs', v: 'Components documented with usage, rules and constraints — secured for both designers and devs.' },
            { k: 'Workflow automation', v: 'Sketch → Figma migration at Orange, with a brand-new UI Kit.' },
            { k: 'Multi-mode theming', v: 'Light / dark switch shipped on the FDJ mobile app, driven by tokens.' },
          ],
        },
        {
          id: 'ai',
          tag: 'C',
          title: 'Design AI',
          oneLiner: 'No hype. Just leverage where the system already exists.',
          method: [
            'Use the design system as the AI\'s grammar',
            'Automate the boring: docs, alt-text, changelogs',
            'Augment review: flag drift, suggest tokens',
            'Keep humans in every creative loop',
          ],
          proof: [
            { k: 'Auto-documentation', v: 'Component props → MDX docs + usage examples, generated on each merge.' },
            { k: 'Design assistant', v: 'In-Figma helper that maps freeform layers to existing tokens.' },
            { k: 'System acceleration', v: 'New screens scaffolded from a brief in minutes, not hours.' },
          ],
        },
        {
          id: 'teach',
          tag: 'D',
          title: 'Teaching · Mentoring',
          oneLiner: 'A system spreads through people, not files.',
          method: [
            'Workshops scoped by role, not seniority',
            '1:1 mentoring on real product work',
            'Public office hours for any designer',
            'Document the why, not just the how',
          ],
          proof: [
            { k: 'ECV Aix-en-Provence', v: 'Speaker session for M1 students on Atomic Design, variables, tokens, documentation, theming.' },
            { k: '40+ designers trained', v: 'Workshops, open hours, tutorials and guides at Société Générale.' },
            { k: 'Exercise: rebuild a component', v: 'Take a legacy button, return a token-driven, accessible, themed one.' },
          ],
        },
      ],
    },
    cases: {
      kicker: '03 — Case studies',
      title: 'Three contexts,\nthree systems lived.',
      items: [
        {
          id: 'sg',
          detailUrl: 'sg.html',
          client: 'Société Générale × Devoteam',
          role: 'Consultant Design System Manager',
          period: 'Mar 2024 — Sep 2025',
          summary: 'Rebuilt and unified the Figma libraries for retail banking — one source for client and advisor surfaces.',
          context: 'Two parallel design systems — one for the client app, one for the advisor tooling. Drift was compounding. Designers spent more time aligning to spec than designing. Devs were rebuilding instead of reusing.',
          problem: 'No shared contract. Libraries were duplicated, hard to navigate, hard to maintain. Adoption was uneven. No documented governance.',
          action: [
            'Restructured both Figma libraries for readability, maintainability and adoption',
            'Set up variables and tokens to automate desktop / mobile variants',
            'Unified client + advisor systems into a single library with dedicated modes',
            'Wrote operational documentation : usage, rules, constraints — for designers and devs',
            'Trained 40+ designers via workshops, open hours, tutorials and guides',
          ],
          result: [
            { k: '40', s: '+', v: 'Designers trained on the new system' },
            { k: '2 → 1', s: '', v: 'Design systems unified' },
            { k: '0', s: '', v: 'Manual desktop/mobile drift remaining' },
            { k: '18', s: ' mo', v: 'Mission length, four releases shipped' },
          ],
        },
        {
          id: 'ecv',
          detailUrl: 'ecv.html',
          client: 'ECV Aix-en-Provence',
          role: 'Speaker — Atomic & Design System',
          period: 'Feb 2025 + Apr 2026 · 2 cohorts',
          summary: 'Two workshops with Master 1 students on building and documenting a Design System from scratch.',
          context: 'M1 students with good UI instincts but no mental models for system thinking. First real contact with Atomic Design, tokens, theming and governance.',
          problem: 'Without solid frameworks for thinking at scale, coherence stays accidental. The risk: producing great screens without knowing how to go from 10 to 100 without breaking everything.',
          action: [
            'Taught Atomic Design fundamentals — atoms, molecules, organisms, templates, pages',
            'Covered variables, token types (primitive, semantic, component) and naming conventions',
            'Each student built a complete Figma library from color palette to templates',
            'Hands-on sessions on modular decomposition and component reuse',
            'Each student documented every component: usage, rules, constraints, variants',
          ],
          result: [
            { k: '2', s: '', v: 'Consecutive years, two cohorts trained' },
            { k: '14', s: '', v: 'M1 students trained end-to-end' },
            { k: '14', s: '', v: 'Design systems documented and delivered' },
            { k: '5', s: ' d', v: 'Intensive format, repeatable' },
          ],
        },
        {
          id: 'fdj',
          detailUrl: 'fdj.html',
          client: 'Française des Jeux × Devoteam',
          role: 'Consultant Product Designer · System Designer',
          period: 'Jul 2022 — Dec 2023',
          summary: 'Owned the mobile design system end-to-end — from contributor to referent — and shipped a token-driven light/dark mode.',
          context: 'A mobile gaming app with a fragmented Figma library. Variants were maintained by hand. No theming contract. The same component existed in subtly different versions across screens.',
          problem: 'Designers and developers were both slowed down. Visual consistency was a coin flip. Light/dark could not be shipped without a tokenized base.',
          action: [
            'Designed and improved core flows alongside system work',
            'Took ownership of the mobile design system, first as a designer, then as referent',
            'Rebuilt the Figma library — automated variants, tokens, light/dark switch',
            'Held graphical consistency across the app and tooled the design + dev workflow',
            'Worked alongside engineering and product to land components cleanly',
          ],
          result: [
            { k: '1', s: '', v: 'Token-driven light/dark mode shipped' },
            { k: '100', s: '%', v: 'Variants automated, no manual upkeep' },
            { k: '17', s: ' mo', v: 'Mission, system referent role' },
            { k: '1', s: '', v: 'Library, one source for the mobile app' },
          ],
        },
      ],
    },
    experience: {
      kicker: '04 — Experience',
      title: 'Eight years,\nsix operating contexts.',
      items: [
        {
          org: 'ECV Aix-en-Provence',
          role: 'Speaker — Atomic & Design System',
          period: 'Apr 2026',
          location: 'Aix-en-Provence',
          impact: [
            'Workshop for M1 students on building and documenting a Design System',
            'Atomic Design, variables, design tokens, documentation, theming',
          ],
        },
        {
          org: 'Société Générale × Devoteam',
          role: 'Consultant Design System Manager',
          period: 'Mar 2024 — Sep 2025',
          location: 'Paris · Remote',
          impact: [
            'Restructured the Figma libraries for readability and maintainability',
            'Unified client + advisor systems into one library with dedicated modes',
            'Trained 40+ designers via workshops, open hours and written guides',
          ],
        },
        {
          org: 'ECV Aix-en-Provence',
          role: 'Speaker — Atomic & Design System',
          period: 'Feb 2025',
          location: 'Aix-en-Provence',
          impact: [
            'New workshop session for M1 students — same topic, deeper hands-on',
            'Atomic Design, variables, design tokens, documentation, theming',
          ],
        },
        {
          org: 'Française des Jeux × Devoteam',
          role: 'Consultant Product Designer · System Designer',
          period: 'Jul 2022 — Dec 2023',
          location: 'Paris',
          impact: [
            'Owned the mobile design system, first as designer, then as referent',
            'Rebuilt the Figma library — variants automation, tokens, light/dark switch',
            'Held graphical consistency and tooled the design + dev workflow',
          ],
        },
        {
          org: 'Orange × Niji',
          role: 'Consultant Product Designer',
          period: 'Oct 2021 — Jun 2022',
          location: 'Paris',
          impact: [
            'Reworked and simplified the subscription steps; ran user tests to validate',
            'Migrated the team from Sketch to Figma',
            'Built a new UI Kit aligned with the rebuilt flows',
          ],
        },
        {
          org: 'Funecap × Niji',
          role: 'Consultant Product Designer · System Designer',
          period: 'Apr 2021 — Sep 2021',
          location: 'Paris',
          impact: [
            'Rebuilt the Figma library end-to-end',
            'Held graphical consistency and tooled the design + dev workflow',
          ],
        },
        {
          org: 'Mister Menuiserie',
          role: 'Product Designer · System Designer',
          period: 'Mar 2018 — Feb 2021',
          location: 'France',
          impact: [
            'Modernized and harmonized 7 e-commerce sites away from a hard-discount image',
            'Built simple, effective product configurators',
            'Set up a coherent design system across all 7 platforms',
          ],
        },
      ],
    },
    recos: {
      kicker: '05 — Recommendations',
      title: 'What people who shipped with me said.',
      items: [
        {
          quote: 'Martin played a central role in scaling AVENIR — Société Générale Retail Banking\'s Design System. His Figma library architecture, his support of designers and developers, and his ability to set and apply a clear short and long-term vision make him a very complete Design System Manager.',
          name: 'Salomé M.',
          role: 'Design Ops · Devoteam CreativeTech',
        },
        {
          quote: 'Martin was essential to setting up the Design System at Société Générale. His Figma expertise let us roll out design tokens across every multi-theme component. The slot pattern he set up to automate responsive rendering massively improved designer throughput.',
          name: 'Ivan T.',
          role: 'Application Lead · Société Générale',
        },
        {
          quote: 'It\'s thanks to Martin\'s relentless work that we shipped one of the most structuring DS projects: the token matrix. Today, we\'ve gained tremendous speed and flexibility in how we design components. Beyond the system work, Martin was always there to help and train Product Designers.',
          name: 'Justine L.',
          role: 'Design System Designer',
        },
        {
          quote: 'Martin has a 360° view of design system rules, with exemplary rigor. His ability to structure, evolve and spread a coherent DS culture made the work of every Product Designer and dev team materially easier. Pragmatic, accessible, fast — I recommend him without hesitation.',
          name: 'Marta M.',
          role: 'Product Designer Manager · Upgrade',
        },
        {
          quote: 'Working with Martin was as enjoyable as it was enriching. He brings calm, trust and positive momentum to a team. Beyond the technical chops, he\'s a teacher — always available to explain or unblock.',
          name: 'Sarah S.',
          role: 'Product Designer · Devoteam',
        },
        {
          quote: 'Martin excels at managing design systems — it makes teamwork fluid and efficient. He has a real talent for rallying people and sharing ideas in an inspiring way. Technically he\'s top-tier, but what stands out is the human approach.',
          name: 'Marc Q.',
          role: 'Product Designer · FDJ',
        },
      ],
    },
    about: {
      kicker: '06 — About',
      title: 'How I work.',
      now: 'Eight years as a Product Designer focused on systems. Last mission: Design System Manager at Société Générale via Devoteam. Speaker at ECV Aix-en-Provence on Atomic Design and tokens. Based near Marseille for the past two years, full-remote.',
      next: 'Looking for a Lead Design System role, full-remote CDI, in a product team that takes systems seriously. Open to selected freelance work in parallel — system audit, rollout, ops setup.',
      principles: [
        { k: 'Systems beat heroics', v: 'A repeatable process beats a brilliant one-off.' },
        { k: 'Measure or move on', v: 'If a system change has no metric, it isn\'t a change.' },
        { k: 'Spread through people', v: 'Files don\'t adopt themselves. Designers do.' },
        { k: 'Boring on purpose', v: 'Predictable surfaces buy you the budget for ambitious ones.' },
      ],
    },
    contact: {
      kicker: '06 — Contact',
      title: 'Let\'s talk.',
      sub: 'Best for: Lead Design System CDI (remote), or scoped freelance missions — system audit, rollout, ops setup.',
      availability: 'Freelance availability — Q3 2026',
      links: [
        { k: 'LinkedIn', v: 'linkedin.com/in/mmolet', href: 'https://www.linkedin.com/in/mmolet' },
        { k: 'Location', v: 'Marseille or remote' },
      ],
    },
  },
  fr: {
    nav: ['Sommaire', 'Études de cas', 'Parcours', 'Contact'],
    meta: {
      role: 'Product Designer · Design System & Design Ops',
      location: 'Marseille / Remote',
      status: 'Ouvert au CDI · Freelance dispo',
      lastUpdated: 'Avr. 2026',
      filename: 'martin-molet.portfolio.v4',
    },
    home: {
      kicker: '01 — Sommaire',
      title: 'J\'aide les équipes à\nscale\nleur DS.',
      sub: '8 ans de Product Design, spécialisé design system et design ops. De l\'e-commerce à la banque retail, je transmets aux équipes une façon de travailler, pas seulement des composants.',
      cta1: 'Voir les études',
      cta2: 'Me contacter',
      metrics: [
        { value: 40, suffix: '+', label: 'Designers formés sur le système Société Générale', note: 'Ateliers, open hours, tutoriels et guides écrits de l\'adoption, pas de l\'imposition.' },
        { value: 2, suffix: ' → 1', label: 'Design systems fusionnés en une seule librairie', note: 'Systèmes client + conseiller réunis, avec des modes dédiés. Moins de doublons, moins de dérive.' },
        { value: 8, suffix: '+', label: 'Ans à livrer des systèmes en production', note: '7 sites e-commerce, banque retail, mobile gaming, souscription telecom.' },
      ],
    },
    work: {
      kicker: '02 — Practices',
      title: 'Quatre practices,\nun seul modèle opérationnel.',
      sub: 'Je traite le design comme une infrastructure. Chaque practice est une couche de cette pile.',
      sections: [
        {
          id: 'ds',
          tag: 'A',
          title: 'Design System',
          oneLiner: 'Une librairie, ce n\'est pas un système. Le système, c\'est le contrat.',
          method: [
            'Auditer les librairies existantes — composants, tokens, dérives, dette',
            'Définir le contrat — nommage, structure, gouvernance',
            'Tokeniser par le bas — primitives → sémantique → composant',
            'Migrer par vagues, jamais d\'un seul bloc',
            'Mesurer l\'adoption, pas la production',
          ],
          proof: [
            { k: 'Refonte Figma', v: 'Librairies Société Générale restructurées pour la lisibilité, la maintenabilité et l\'adoption.' },
            { k: 'Variables & tokens', v: 'Déclinaisons desktop / mobile automatisées. Les erreurs manuelles tombent à zéro.' },
            { k: '2 → 1 système', v: 'Systèmes client et conseiller réunis en une seule librairie avec modes dédiés.' },
          ],
        },
        {
          id: 'ops',
          tag: 'B',
          title: 'Design Ops',
          oneLiner: 'Le bon chemin doit être le chemin naturel.',
          method: [
            'Cartographier le cycle design de bout en bout',
            'Repérer les frictions — handoffs, revues, nommage, fichiers',
            'Standardiser ce qui doit l\'être, laisser de la liberté sur le reste',
            'Documenter usages, règles et contraintes — pour designers et devs',
            'Animer des open hours pour que le système reste une conversation vivante',
          ],
          proof: [
            { k: 'Documentation opérationnelle', v: 'Composants documentés avec usages, règles et contraintes — sécurisés pour designers et développeurs.' },
            { k: 'Automatisation des workflows', v: 'Migration Sketch → Figma chez Orange, avec un UI Kit entièrement refait.' },
            { k: 'Theming multi-modes', v: 'Switch light / dark livré sur l\'app mobile FDJ, piloté par tokens.' },
          ],
        },
        {
          id: 'ai',
          tag: 'C',
          title: 'Design AI',
          oneLiner: 'Pas de hype. Du levier là où le système existe déjà.',
          method: [
            'Utiliser le design system comme grammaire de l\'IA',
            'Automatiser ce qui est répétitif : docs, alt-text, changelogs',
            'Outiller le review : détecter les dérives, proposer des tokens',
            'Garder l\'humain dans chaque boucle créative',
          ],
          proof: [
            { k: 'Auto-documentation', v: 'Props → MDX + exemples d\'usage, générés à chaque merge.' },
            { k: 'Assistant design', v: 'Helper Figma qui associe les calques libres aux tokens existants.' },
            { k: 'Génération accélérée', v: 'Des écrans complets depuis un brief — en quelques minutes, pas en heures.' },
          ],
        },
        {
          id: 'teach',
          tag: 'D',
          title: 'Transmission · Mentorat',
          oneLiner: 'Un système se transmet par les gens, pas par les fichiers.',
          method: [
            'Workshops calés sur le rôle, pas sur le niveau',
            'Mentorat 1:1 sur du vrai produit',
            'Open hours ouvertes à tous les designers',
            'Documenter le pourquoi, pas seulement le comment',
          ],
          proof: [
            { k: 'ECV Aix-en-Provence', v: 'Atelier M1 — Atomic Design, variables, tokens, documentation, theming.' },
            { k: '40+ designers formés', v: 'Ateliers, open hours, tutoriels et guides écrits chez Société Générale.' },
            { k: 'Exercice fil rouge', v: 'Reprendre un bouton legacy et le rendre token-driven, accessible, thémé.' },
          ],
        },
      ],
    },
    cases: {
      kicker: '03 — Études de cas',
      title: '3 environements.',
      items: [
        {
          id: 'sg',
          detailUrl: 'sg.html',
          client: 'Société Générale × Devoteam',
          role: 'Consultant Design System Manager',
          period: 'Mars 2024 — Sept. 2025',
          summary: 'Refonte et unification des librairies Figma pour la banque retail : une source unique pour le client et le conseiller.',
          context: 'Deux design systems en parallèle : un pour l\'app client, un pour l\'interface conseiller. La dérive s\'accumulait. Les designers passaient plus de temps à se recaler sur les specs qu\'à concevoir.',
          problem: 'Aucune règle claire. Des librairies dupliquées, difficiles à naviguer et à maintenir. Une adoption inégale selon les équipes. Aucune gouvernance documentée.',
          action: [
            'Réorganisation des librairies Figma — classement alphabétique aligné sur Storybook',
            '280+ tokens de taille et 230+ tokens de couleur — une librairie, plusieurs modes',
            'Fusion des systèmes client + conseiller en une seule librairie thématisée',
            'Refonte de 25+ composants et reconstruction de 30+ icônes — slots, variables, variants rationalisés',
            'Formation de 40+ designers via ateliers, open hours, tutoriels et guides écrits',
          ],
          result: [
            { k: '40', s: '+', v: 'Designers formés au nouveau système' },
            { k: '280', s: '+', v: 'Tokens de taille — source unique de vérité' },
            { k: '230', s: '+', v: 'Tokens de couleur sur deux modes thématisés' },
            { k: '4×', s: '', v: 'Déclinaison d\'écrans plus rapide' },
          ],
        },
        {
          id: 'ecv',
          detailUrl: 'ecv.html',
          client: 'ECV Aix-en-Provence',
          role: 'Intervenant — Atomic & Design System',
          period: 'Févr. 2025 + Avr. 2026 · 2 promotions',
          summary: 'Deux ateliers avec des étudiants Master 1 pour apprendre à concevoir et documenter un Design System de A à Z.',
          context: 'Premier vrai contact avec l\'Atomic Design, les tokens, le theming et la gouvernance.',
          problem: 'Le risque : produire de beaux écrans sans savoir passer de 10 à 100 sans tout casser.',
          action: [
            'Fondamentaux de l\'Atomic Design — atoms, molecules, organisms, templates, pages',
            'Variables, types de tokens (primitive, sémantique, composant) et nommage',
            'Chaque étudiant construit une librairie Figma complète — de la palette aux templates',
            'Ateliers pratiques sur la décomposition modulaire et la réutilisation',
            'Chaque étudiant documente ses composants : usages, règles, contraintes, variantes',
          ],
          result: [
            { k: '2', s: '', v: 'Années consécutives, deux promotions formées' },
            { k: '14', s: '', v: 'Étudiants M1 formés de bout en bout' },
            { k: '14', s: '', v: 'Design systems documentés et livrés' },
            { k: '5', s: ' j', v: 'Format intensif, reproductible' },
          ],
        },
        {
          id: 'fdj',
          detailUrl: 'fdj.html',
          client: 'Française des Jeux × Devoteam',
          role: 'Consultant Product Designer · System Designer',
          period: 'Juil. 2022 — Déc. 2023',
          summary: 'Prise en main du design system mobile de bout en bout, de contributeur à référent, avec un mode light/dark piloté par tokens.',
          context: 'Une app mobile gaming avec une librairie Figma morcelée. Les variantes étaient maintenues à la main. Aucun contrat de thème. Le même composant existait en plusieurs versions légèrement différentes selon les écrans.',
          problem: 'Designers et développeurs ralentis. La cohérence visuelle était aléatoire. Impossible de livrer le light/dark sans base tokenisée.',
          action: [
            'Concevoir et améliorer les parcours en parallèle du DS',
            'Prendre en main le design system mobile, d\'abord designer, puis référent',
            'Refonte complète de la librairie Figma : variantes automatisées, tokens, switch light/dark',
            'Tenir la cohérence graphique sur l\'ensemble de l\'app et outiller le workflow design + dev',
            'Travailler avec les équipes eng et produit pour intégrer les composants proprement',
          ],
          result: [
            { k: '1', s: '', v: 'Mode light/dark piloté par tokens livré en production' },
            { k: '100', s: '%', v: 'Variantes automatisées, zéro maintenance manuelle' },
            { k: '17', s: ' mois', v: 'Mission, dont le rôle de référent DS' },
            { k: '1', s: '', v: 'Librairie unique : une source pour toute l\'app' },
          ],
        },
      ],
    },
    experience: {
      kicker: '04 — Parcours',
      title: 'Huit ans,\nsix contextes.',
      items: [
        {
          org: 'ECV Aix-en-Provence',
          role: 'Intervenant — Atomic & Design System',
          period: 'Avr. 2026',
          location: 'Aix-en-Provence',
          impact: [
            'Atelier M1 pour la deuxième années consécutive sur la conception et la documentation d\'un Design System',
            'Atomic Design, variables, design tokens, documentation Supernova, theming',
          ],
        },
        {
          org: 'Société Générale × Devoteam',
          role: 'Consultant Design System Manager',
          period: 'Mars 2024 — Sept. 2025',
          location: 'Paris · Remote',
          impact: [
            'Restructuration des librairies Figma : lisibilité, maintenabilité, adoption',
            'Fusion des librairies client + conseiller en une librairie avec modes dédiés',
            '40+ designers formés via ateliers, open hours et guides écrits',
          ],
        },
        {
          org: 'ECV Aix-en-Provence',
          role: 'Intervenant — Atomic & Design System',
          period: 'Févr. 2025',
          location: 'Aix-en-Provence',
          impact: [
            'Atelier M1 sur la conception et la documentation d\'un Design System',
            'Atomic Design, variables, design tokens, documentation Zeroheight, theming',
          ],
        },
        {
          org: 'Française des Jeux × Devoteam',
          role: 'Consultant Product Designer · System Designer',
          period: 'Juil. 2022 — Déc. 2023',
          location: 'Paris',
          impact: [
            'En charge du design system mobile — d\'abord designer, puis référent',
            'Refonte Figma : variantes automatisées, tokens, switch light/dark',
            'Cohérence graphique tenue sur l\'app, workflow design + dev outillé',
          ],
        },
        {
          org: 'Orange × Niji',
          role: 'Consultant Product Designer',
          period: 'Oct. 2021 — Juin 2022',
          location: 'Paris',
          impact: [
            'Refonte et simplification des parcours de souscription, validés par tests utilisateurs',
            'Migration de l\'équipe de Sketch vers Figma',
            'Création d\'un nouveau UI Kit aligné sur les parcours refondus',
          ],
        },
        {
          org: 'Funecap × Niji',
          role: 'Consultant Product Designer · System Designer',
          period: 'Avr. 2021 — Sept. 2021',
          location: 'Paris',
          impact: [
            'Refonte complète de la librairie Figma de zéro',
            'Cohérence graphique tenue sur l\'ensemble des écrans, workflow design + dev',
          ],
        },
        {
          org: 'Mister Menuiserie',
          role: 'Product Designer · System Designer',
          period: 'Mars 2018 — Févr. 2021',
          location: 'France',
          impact: [
            'Modernisation et harmonisation de 7 sites e-commerce, sortie de l\'image hard-discount',
            'Conception de configurateurs produits simples et efficaces',
            'Mise en place d\'un design system cohérent sur les 7 plateformes',
          ],
        },
      ],
    },
    recos: {
      kicker: '05 — Recommandations',
      title: 'On a travaillé ensemble.',
      items: [
        {
          quote: 'Martin a eu un rôle central dans le passage à l\'échelle du Design System AVENIR de la Banque de Détails de la Société Générale. Son expertise sur l\'architecture Figma, son accompagnement des Product Designers et développeurs, et sa capacité à appliquer une vision claire à court et long terme en font un Design System Manager très complet.',
          name: 'Salomé M.',
          role: 'Design Ops Manager · SG x Devoteam',
        },
        {
          quote: 'Martin a eu un rôle essentiel dans la mise en place du Design System à la Société Générale. Son expertise Figma nous a permis de déployer les design tokens sur l\'ensemble des composants multi-thèmes. La mise en place de slots pour automatiser le rendu responsive a grandement facilité la production des designers.',
          name: 'Ivan T.',
          role: 'Responsable d\'application · SG',
        },
        {
          quote: 'C\'est grâce au travail acharné de Martin que nous avons pu lancer l\'un des projets les plus structurants du DS : la matrice de tokens. On y a énormément gagné en rapidité et en flexibilité sur la conception des composants. Au-delà du système, Martin a toujours été présent pour aider et former les Product Designers.',
          name: 'Justine L.',
          role: 'Design System Designer · SG x Devoteam',
        },
        {
          quote: 'Martin possède une vision 360° des règles design system, avec une rigueur exemplaire. Sa capacité à structurer, faire évoluer et diffuser une culture DS cohérente a considérablement facilité le travail des Product Designers et des équipes dev. Pragmatique, accessible, rapide — je le recommande sans hésitation.',
          name: 'Marta M.',
          role: 'Product Designer Manager · SG x Upgrade',
        },
        {
          quote: 'Travailler avec Martin a été aussi agréable qu\'enrichissant. Il apporte de la sérénité, de la confiance et une dynamique positive à toute l\'équipe. Au-delà des compétences techniques, c\'est un pédagogue — toujours disponible pour expliquer ou débloquer.',
          name: 'Sarah S.',
          role: 'Product Designer · SG x Devoteam',
        },
        {
          quote: 'Martin excelle dans la gestion des design systems, ce qui rend le travail d\'équipe fluide et efficace. Il a un vrai talent pour rassembler et partager ses idées de manière inspirante. Techniquement au top, mais ce qui le distingue, c\'est l\'approche humaine.',
          name: 'Marc Q.',
          role: 'Product Designer · FDJ x Devoteam',
        },
      ],
    },
    contact: {
      kicker: '06 — Contact',
      title: 'Contact.',
      sub: 'Idéal : poste de Lead Design System CDI (remote) ou mission freelance ciblée — audit système, déploiement, structuration des ops.',
      availability: 'Disponibilité freelance — ASAP',
      links: [
        { k: 'LinkedIn', v: 'linkedin.com/in/mmolet', href: 'https://www.linkedin.com/in/mmolet' },
        { k: 'Localisation', v: 'Marseille ou remote' },
      ],
    },
  },
};
window.CONTENT = CONTENT;
